### ISSUE TITLE
Using the same property in different declarations inside media queries are reported as duplicate

### ISSUE THREAD

**Issue by d-claassen** [kalidasya/sonar-css#6]
When I have several declarations inside a media query, and those different declarations contain the same properties, an violation is created. In the example below the second `border-color` is marked as a duplicate property.

``` scss
@media (min-width: 320px) {
  .box1 {
    border-color: orange; 
  }
  .box2 {
    border-color: orangered;
  }
}
```
